language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --no-dev
  - travis_retry composer require --dev "phpunit/phpunit:~4.0"

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
